name: Renovate

on:
  workflow_dispatch:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  helm-releases:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Generate Token
      uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: "${{ secrets.BOT_APP_ID }}"
        private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

    - name: Install yq
      run: |
        sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
    - name: Renovate Helm Releases
      uses: k8s-at-home/renovate-helm-releases@v1
      with:
        cluster-path: "./"

    - name: Create pull request for HelmRelease annotations
      uses: peter-evans/create-pull-request@v4
      with:
        token: "${{ steps.generate-token.outputs.token }}"
        branch: helm-release-annotations
        title: "[renovate] create helmrelease annotations [ci-skip]"
        signoff: true
        committer: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
        author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
        commit-message: Create renovatebot helmrelease annotations
        body: |
          Signed-off-by: dkw99 <dkw99@users.noreply.github.com>
        labels: renovate/helm-release-annotations